name: bot_path_drawer_example
description: Example app for bot_path_drawer.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bot_path_drawer:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
